# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
- repo: self

pool:
  name: Default
  demands:
   - agent.name -equals jaya1 
stages:
- stage: Validate
  jobs: 
  - job: Validate
    continueOnError: false
    steps:
    #- publish: 1-terraform
      #artifact: terraform_out
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
      displayName: 'Use Terraform v0.12.6'
      inputs:
        terraformVersion: 0.12.6
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'terraform init'
      inputs:
        command: init
        workingDirectory: $(System.DefaultWorkingDirectory)
        backendType: azurerm
        backendServiceArm: 'AKSTerraform'
        backendAzureRmResourceGroupName: 'AKSTerraform-RG'
        backendAzureRmStorageAccountName: 'jayaaksterraform '
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'demo.terraform.tfstate'
    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
      displayName: 'terraform validate'
      inputs:
        command: validate
        workingDirectory: $(System.DefaultWorkingDirectory)
 

- stage: Deploy
  jobs:
    # track deployments on the environment
  - deployment: Deploy_Terraform
    pool:
      name: Default
      demands:
       - agent.name -equals jaya1 
    #pool:
      #vmImage: 'ubuntu-latest'
    # creates an environment if it doesn’t exist
    environment: 'DEV'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
          # - download: current
          #   artifact: terraform_out
- script: |
  terraform init -reconfigure
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
            displayName: 'terraform init'
            inputs:
              command: init 
              workingDirectory: $(System.DefaultWorkingDirectory)
              backendType: azurerm
              backendServiceArm: 'AKSTerraform'
              backendAzureRmResourceGroupName: 'AKSTerraform-RG'
              backendAzureRmStorageAccountName: 'jayaaksterraform '
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'demo.terraform.tfstate'
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
            displayName: 'terraform plan'
            inputs:
              command: plan
              workingDirectory: $(System.DefaultWorkingDirectory)
              environmentServiceName: 'AKSTerraform'
              secureVarsFile: 'aks_conf.tfvars'
              commandOptions: '-out $(System.DefaultWorkingDirectory)/terraform_aks_out'
              terraformVersion: 0.12.6
          - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
            displayName: 'terraform apply'
            inputs:
              command: apply
              workingDirectory: $(System.DefaultWorkingDirectory)
              environmentServiceName: 'AKSTerraform'
              commandOptions: $(System.DefaultWorkingDirectory)/terraform_aks_out'
              terraformVersion: 0.12.6
            
